name: Build macOS App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pyinstaller
        pip install python-docx python-pptx PyQt5

    - name: Build .app
      run: |
        pyinstaller --onefile --windowed doc_to_pptx_gui_progress.py
        ls dist

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: doc_to_pptx_gui_progress-mac
        path: dist/*
